name: Build and Push Docker Image
on:
  push:
    branches:
      - develop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: keepintouch/keepintouch-fe:develop

    # 인스턴스 접속 & 애플리케이션 실행
    - name: Connect to Server & Execute Application
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEV_FE_HOST }}
        username: ${{ secrets.DEV_FE_USERNAME }}
        key: ${{ secrets.DEV_FE_SSH_KEY }}
        port: 22
        script: |
          sudo docker stop $(docker ps -a -q) 
          sudo docker rm $(docker ps -a -q) 
          sudo docker pull <docker_hub_username>/<docker_image_name>:develop
          sudo docker run -d -p 3000:3000 --name <container_name> <docker_hub_username>/<docker_image_name>