name: Build and Push Docker Image
on:
  push:
    branches:
      - release/v2
    paths-ignore: ./*.md
  # inputs:
  #   repo_name :
  #     description: "the name of the target repository"
  #     type: string
  #     required: true
  #     default: 'keepintouch-fe'
  #   container_name :
  #     description: "the name of the target container to run"
  #     type: string
  #     required: true
  #     default: 'keepintouch-fe'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: keepintouch/keepintouch-fe:release-v2

      # 인스턴스 접속 & 애플리케이션 실행
      - name: Connect to Server & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_FE_HOST }}
          username: ${{ secrets.DEV_FE_USERNAME }}
          key: ${{ secrets.DEV_FE_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop keepintouch-fe-v2
            sudo docker rm keepintouch-fe-v2
            sudo docker rmi keepintouch-fe:release-v2
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/keepintouch-fe:release-v2
            sudo docker run -d -p 8000:8000 --name keepintouch-fe-v2 ${{ secrets.DOCKERHUB_USERNAME }}/keepintouch-fe:release-v2
      
      ## created at 20241220
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: developement
          version : ${{ github.sha }}